Login_System/Login_System/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from myBasicApp import views

urlpatterns = [
   path('',views.home,name='home'),
    url('admin/', admin.site.urls),
    url('myapp/',include('myBasicApp.urls'))
   
    
]

Login_System/myBasicApp/urls.py
from django.urls import path
from . import views
app_name='myBasicApp'
urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
]

Login_System/myBasicApp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Userinfo(models.Model):
    user=models.OneToOneField(User,on_delete=callable)

Login_System/myBasicApp/forms.py
from .models import Userinfo
from django import forms
from django.contrib.auth.models import User

class UserinfoForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),help_text=None)
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    class Meta():
        model=User
        fields=('username','password','email')
        

Login_System/myBasicApp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .forms import UserinfoForm
from .models import Userinfo
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def home(request):
    return render(request,'myBasicApp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request,'myBasicApp/index.html')

def user_login(request):
    
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
               
            else:
                print("ACcount not Active")
        else:
            return HttpResponse("Invalid Login")
        
    else:
        return render(request,'myBasicApp/login.html')

def register(request):
    registered=False
    if request.method == 'POST':
        user_form=UserinfoForm(data=request.POST)
        if user_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True
        else:
            return HttpResponse(user_form.errors)
    else:
        user_form=UserinfoForm()

    return render(request,'myBasicApp/register.html',{'fn':user_form})

Login_System/templates/myBasicApp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login_System</title>
             <link rel="stylesheet" href="/static/css/style.css">
             <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
             <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
             <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
             <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
             <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
    </head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

Login_System/templates/myBasicApp/index.html
{% extends 'myBasicApp/base.html' %}
{% block content %}
<div class="jumbotron bg-dark">
    <ul class="navbar-nav navbar-light  navbar-expand justify-content-center">
    <li class="nav-item m-4"><a href="{% url 'home' %}" class="nav-link lead">Home</a></li>
    <li class="nav-item m-4"><a href="{% url 'myBasicApp:register' %}" class="nav-link lead">Register</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item m-4"><a href="{% url 'myBasicApp:logout' %}" class="nav-link lead">LogOut</a></li>
    {% else %}
    <li class="nav-item m-4"><a href="{% url 'myBasicApp:login' %}" class="nav-link lead">LogIn</a></li>

{% endif %}
</ul></div>
<div class="jumbotron my-5 text-center bg-primary text-white">
<h1>Welcome To Login System</h1>
{% if user.is_authenticated %}
<p class="lead mt-3 text-dark">You have been Logged IN Succesfully</p>
{% else %}
<p class="lead mt-3">Please Login With Your Credentials / Register Yourself</p>
</ul></div>
{% endif %}

</div>
{% endblock %}

Login_System/templates/myBasicApp/login.html
{% extends 'myBasicApp/base.html' %}

{% block content %}
<div class="jumbotron">
<h1 class="my-5 text-primary"> Login </h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username :</label>
        <input type="text" name="username" placeholder="Username.." class="form-control">
        <label for="password">Password :</label>
        <input type="password" name="password" placeholder="Password.." class="form-control">
        <input type="submit" value="Login" class="btn btn-primary mt-4">
    </div>
</form>
</div>
{% endblock %}

Login_System/templates/myBasicApp/register.html
{% extends 'myBasicApp/base.html' %}

{% block content %}
<div class="jumbotron">
<h1 class="text-primary my-5">Signup</h1>
{% if fn.registered %}
<h3>Thank You for Registering to Our site</h3>
{% else %}
<form method="post" class="form-group">
    {% csrf_token %}
    {{ fn.as_p }}
    <input type="submit" class="btn btn-primary mt-2" value="Register">
</form>
</div>
{% endif %}
{% endblock %}